-------------------------------------------------------- USER 테이블
DROP TABLE TB_USER;

CREATE TABLE TB_USER
(
    USER_ID VARCHAR2(30) ,
    PASSWORD VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    GENDER CHAR,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(50),
    NICKNAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30),
    CREATE_ACCOUNT_DATE DATE DEFAULT SYSDATE,
    DELETE_ACCOUNT_YN CHAR DEFAULT 'N' CHECK(DELETE_ACCOUNT_YN IN ('Y','N')) NOT NULL,
    IS_ADMIN VARCHAR2(10) DEFAULT 'USER' CHECK(IS_ADMIN IN ('ADMIN','USER')),
    GRADE VARCHAR2(10) DEFAULT 'SILVER',
    USER_IMG VARCHAR2(500),
    USER_INFO VARCHAR2(1000),
    
    CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID)
);
-------------------------------------------------------- USER 테이블

CREATE TABLE SALESHOP (
    SALESHOP_CODE NUMBER PRIMARY KEY,
    SALESHOP_NAME VARCHAR2(30) NOT NULL,
    SALESHOP_URL VARCHAR2(100)
);

CREATE TABLE HOSPITAL (
    HOSPITAL_CODE NUMBER PRIMARY KEY,
    HOSPITAL_NAME VARCHAR2(30) NOT NULL,
    HOSPITAL_ADDRESS VARCHAR2(100)
);

CREATE TABLE PRODUCT_REVIEW (
    PRODUCT_REVIEW_CODE NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30),
    PRODUCT_REVIEW_DATE DATE DEFAULT SYSDATE,
    SALESHOP_CODE NUMBER,
    PRODUCT_REVIEW_THUM VARCHAR2(100),
    PRODUCT_REVIEW_TITLE VARCHAR2(50) NOT NULL,
    PRODUCT_REVIEW_VIEWS NUMBER DEFAULT 0,
    PRODUCT_REVIEW_DESC VARCHAR2(1000),
    PRODUCT_REVIEW_IMG VARCHAR2(100),
    PRODUCT_REVIEW_LIKE NUMBER DEFAULT 0,
    PRODUCT_REVIEW_REPORT_YN CHAR(1) DEFAULT 'N' CHECK(PRODUCT_REVIEW_REPORT_YN IN ('Y', 'N')) NOT NULL
);

CREATE TABLE PR_COMMENT (
    PR_COMMENT_CODE NUMBER PRIMARY KEY,
    PRODUCT_REVIEW_CODE NUMBER,
    USER_ID VARCHAR2(30),
    PR_COMMENT_DATE DATE DEFAULT SYSDATE,
    PR_COMMENT_DESC VARCHAR2(500) NOT NULL,
    PR_COMMENT_IMG VARCHAR2(100),
    SUPER_PR_COMMENT_CODE NUMBER,
    PR_COMMENT_REPORT_YN CHAR(1) DEFAULT 'N' CHECK(PRODUCT_REVIEW_REPORT_YN IN ('Y', 'N')) NOT NULL
);

CREATE TABLE VIDEO_INFO (
    VIDEO_INFO_CODE NUMBER PRIMARY KEY,
    VIDEO_INFO_TITLE VARCHAR2(50) NOT NULL,
    VIDEO_INFO_VIEWS NUMBER DEFAULT 0,
    VIDEO_INFO_DATE DATE DEFAULT SYSDATE,
    VIDEO_INFO_URL VARCHAR2(100),
    VIDEO_INFO_KIND VARCHAR2(30),
    VIDEO_INFO_LIKE NUMBER DEFAULT 0,
    VIDEO_INFO_REPORT_YN CHAR(1) DEFAULT 'N' CHECK(PRODUCT_REVIEW_REPORT_YN IN ('Y', 'N')) NOT NULL
);

CREATE TABLE VI_COMMENT (
    VI_COMMENT_CODE NUMBER PRIMARY KEY,
    VIDEO_INFO_CODE NUMBER,
    USER_ID VARCHAR2(30),
    VI_COMMENT_DATE DATE DEFAULT SYSDATE,
    VI_COMMENT_DESC VARCHAR2(500) NOT NULL,
    VI_COMMENT_IMG VARCHAR2(100),
    SUPER_VI_COMMENT_CODE NUMBER,
    VI_COMMENT_REPORT_YN CHAR(1) DEFAULT 'N' CHECK(PRODUCT_REVIEW_REPORT_YN IN ('Y', 'N')) NOT NULL
);

CREATE TABLE HOSPITAL_REVIEW (
    HOSPITAL_REVIEW_CODE NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30),
    HOSPITAL_CODE NUMBER,
    HOSPITAL_REVIEW_VIEWS NUMBER DEFAULT 0,
    HOSPITAL_REVIEW_DATE DATE DEFAULT SYSDATE,
    HOSPITAL_REVIEW_TITLE VARCHAR2(50) NOT NULL,
    HOSPITAL_REVIEW_DESC VARCHAR2(1000),
    HOSPITAL_REVIEW_IMG VARCHAR2(100),
    HOSPITAL_REVIEW_LIKE NUMBER DEFAULT 0,
    HOSPITAL_REVIEW_REPORT_YN CHAR(1) DEFAULT 'N' CHECK(PRODUCT_REVIEW_REPORT_YN IN ('Y', 'N')) NOT NULL
);

CREATE TABLE HR_COMMENT (
    HR_COMMENT_CODE NUMBER PRIMARY KEY,
    HOSPITAL_REVIEW_CODE NUMBER,
    USER_ID VARCHAR2(30),
    HR_COMMENT_DATE DATE DEFAULT SYSDATE,
    HR_COMMENT_DESC VARCHAR2(500) NOT NULL,
    HR_COMMENT_IMG VARCHAR2(100),
    SUPER_HR_COMMENT_CODE NUMBER,
    HR_COMMENT_REPORT_YN CHAR(1) DEFAULT 'N' CHECK(PRODUCT_REVIEW_REPORT_YN IN ('Y', 'N')) NOT NULL
);

CREATE SEQUENCE SEQ_SALESHOP;
CREATE SEQUENCE SEQ_HOSPITAL;
CREATE SEQUENCE SEQ_PRODUCT_REVIEW;
CREATE SEQUENCE SEQ_PR_COMMENT;
CREATE SEQUENCE SEQ_VIDEO_INFO;
CREATE SEQUENCE SEQ_VI_COMMENT;
CREATE SEQUENCE SEQ_HOSPITAL_REVIEW;
CREATE SEQUENCE SEQ_HR_COMMENT;

ALTER TABLE PRODUCT_REVIEW ADD CONSTRAINT PRODUCT_REVIEW_SALESHOP_CODE_FK FOREIGN KEY(SALESHOP_CODE) REFERENCES SALESHOP;
