-------------------------------------------------------- USER 테이블
DROP TABLE TB_USER;

CREATE TABLE TB_USER
(
    USER_ID VARCHAR2(30) ,
    PASSWORD VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    GENDER CHAR,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(50),
    NICKNAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30),
    CREATE_ACCOUNT_DATE DATE DEFAULT SYSDATE,
    DELETE_ACCOUNT_YN CHAR DEFAULT 'N' CHECK(DELETE_ACCOUNT_YN IN ('Y','N')) NOT NULL,
    IS_ADMIN VARCHAR2(10) DEFAULT 'USER' CHECK(IS_ADMIN IN ('ADMIN','USER')),
    GRADE VARCHAR2(10) DEFAULT 'SILVER',
    USER_IMG VARCHAR2(500),
    USER_INFO VARCHAR2(1000),
    
    CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID)
);
-------------------------------------------------------- USER 테이블

CREATE TABLE SALESHOP (
    SALESHOP_CODE NUMBER,
    SALESHOP_NAME VARCHAR2(30),
    SALESHOP_URL VARCHAR2(100)
);

CREATE TABLE HOSPITAL (
    HOSPITAL_CODE NUMBER,
    HOSPITAL_NAME VARCHAR2(30),
    HOSPITAL_ADDRESS VARCHAR2(100)
);

CREATE TABLE PRODUCT_REVIEW (
    PRODUCT_REVIEW_CODE NUMBER,
    USER_ID VARCHAR2(30),
    PRODUCT_REVIEW_DATE DATE,
    SALESHOP_CODE NUMBER,
    PRODUCT_REVIEW_THUM VARCHAR2(100),
    PRODUCT_REVIEW_TITLE VARCHAR2(50),
    PRODUCT_REVIEW_VIEWS NUMBER,
    PRODUCT_REVIEW_DESC VARCHAR2(1000),
    PRODUCT_REVIEW_IMG VARCHAR2(50),
    PRODUCT_REVIEW_LIKE NUMBER,
    PRODUCT_REVIEW_REPORT_YN CHAR(1)
);

CREATE TABLE PR_COMMENT (
    PR_COMMENT_CODE NUMBER,
    PRODUCT_REVIEW_CODE NUMBER,
    USER_ID VARCHAR2(30),
    PR_COMMENT_DATE DATE,
    PR_COMMENT_DESC VARCHAR2(500),
    PR_COMMENT_IMG VARCHAR2(100),
    SUPER_PR_COMMENT_CODE NUMBER
);

CREATE TABLE VIDEO_INFORMATION (
    VIDEO_INFORMATION_CODE NUMBER,
    VIDEO_INFORMATION_TITLE VARCHAR2(50),
    VIDEO_INFORMATION_VIEWS NUMBER,
    VIDEO_INFORMATION_DATE DATE,
    VIDEO_INFORMATION_URL VARCHAR2(100),
    VIDEO_INFORMATION_KIND VARCHAR2(30),
    VIDEO_INFORMATION_LIKE NUMBER
);

CREATE TABLE VI_COMMENT (
    VI_COMMENT_CODE NUMBER,
    VIDEO_INFORMATION_CODE NUMBER,
    USER_ID VARCHAR2(30),
    VI_COMMENT_DATE DATE,
    VI_COMMENT_DESC VARCHAR2(500),
    VI_COMMENT_IMG VARCHAR2(50),
    SUPER_VI_COMMENT_CODE NUMBER
);

CREATE TABLE HOSPITAL_REVIEW (
    HOSPITAL_REVIEW_CODE NUMBER,
);

