-- 01 보너스 포함한 연봉이 높은 5명의 사번, 이름, 부서명, 직급, 입사일, 순위 조회
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, ROWNUM
FROM (SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE
      FROM EMPLOYEE
      JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID) JOIN JOB USING(JOB_CODE)
      ORDER BY NVL((SALARY +(BONUS * SALARY)) * 12, SALARY  * 12) DESC)
WHERE ROWNUM <= 5;

-- 02 부서별 급여 합계가 전체 급여 총 합의 20%보다 많은 부서의 부서명, 부서별 급여 합계 조회
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
GROUP BY DEPT_TITLE
HAVING SUM(SALARY) > (SELECT SUM(SALARY) * 0.2
                      FROM EMPLOYEE
                      JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID));

-- 03 WITH을 이용하여 급여 합과 급여 평균 조회
WITH SAL_CAL AS
(SELECT SUM(SALARY) AS "SUM", AVG(SALARY) "AVG"
FROM EMPLOYEE)

SELECT SUM, AVG
FROM SAL_CAL;
