-- 1.
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3.
SELECT PROFESSOR_NAME "교수이름", 100 - SUBSTR(PROFESSOR_SSN,1,2) + 23 "나이"
FROM TB_PROFESSOR;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) "이름"
FROM TB_PROFESSOR;

-- 5.

-- 6.
SELECT TO_CHAR(20201225, 'DY')
FROM DUAL;

-- 7.

-- 8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';

-- 9.
SELECT ROUND(AVG(POINT), 1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10.
SELECT DEPARTMENT_NO "학과번호", COUNT(DEPARTMENT_NO) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12.
--SELECT SUBSTR(TERM_NO, 1, 4) "년도", AVG(POINT) "년도 별 평점"
--FROM TB_GRADE;

-- 13.
--SELECT DEPARTMENT_NO "학과코드명", COUNT(NVL(STUDENT_NO, 0)) "휴학생 수"
--FROM TB_STUDENT
--WHERE ABSENCE_YN = 'Y'
--GROUP BY DEPARTMENT_NO
--ORDER BY DEPARTMENT_NO;

-- 14.
SELECT STUDENT_NAME "동일이름", COUNT(STUDENT_NAME) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) >= 2
ORDER BY STUDENT_NAME;

-- 15.
